var findTheDifference = function(s, t) {
    let so={},to={}
    for(let e of s){
        so[e] = so[e]? so[e]+1 :  1

    }
    for(let e of t){
        if(!so[e]) return e
        so[e]--
    }  
};
// 389. Find the Difference
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.